In [2]:
import pandas as pd
from pathlib import Path
import IMP 
import IMP.atom
import IMP.rmf
import RMF
import random
import numpy as np
import matplotlib.pyplot as plt
import shutil

In [7]:
gsms_dir = Path("/wynton/group/sali/mhancock/mtorc2/samples/exp_14/129/analysis/1/sampcon_3/gsms/10000R/")
gsms_file = Path(gsms_dir, "A.rmf3")
fh_clust = RMF.open_rmf_file_read_only(str(gsms_file))
m_clust = IMP.Model()
h_clust = IMP.rmf.create_hierarchies(fh_clust, m_clust)[0]

In [21]:
s = IMP.atom.Selection(h_clust, chain_id="E", resolution=10)
print(len(s.get_selected_particles()))

41

#### Find structures that are close to either the Kinase domain in the full EM structure or ar enear the Rictor binding site.

In [23]:
dist_dict = dict()
dist_dict["frame"] = list() 
dist_dict["dist_to_kd"] = list() 
dist_dict["dist_to_atp"] = list() 

for i in range(10000):
    if i % 100 == 0: 
        print(i)

    IMP.rmf.load_frame(fh_clust, RMF.FrameID(i))
    dist_dict["frame"].append(i)

    s = IMP.atom.Selection(h_clust, resolution=10, residue_indexes=list(range(145,410)), chain_id="E")

    pids = [pid for pid in s.get_selected_particle_indexes()]

    xyzs = [IMP.core.XYZ(m_clust, pid) for pid in pids]
    
    # Asparagine 279 CA 
    avg = 0
    for xyz in xyzs: 
        d = (xyz.get_coordinates() - IMP.algebra.Vector3D(129.895,58.140,174.139)).get_magnitude()
        avg = avg + d
        
        
    avg = avg / len(xyzs)
    dist_dict["dist_to_kd"].append(avg)
    
    # Asparagine 279 CA 
    avg = 0
    for xyz in xyzs: 
        d = (xyz.get_coordinates() - IMP.algebra.Vector3D(167.651, 131.687, 194.140)).get_magnitude()
        avg = avg + d
        
        
    avg = avg / len(xyzs)
    dist_dict["dist_to_atp"].append(avg)
    
del fh_clust

0
100
200
300
400
500
600
700
800
900
1000
1100
1200
1300
1400
1500
1600
1700
1800
1900
2000
2100
2200
2300
2400
2500
2600
2700
2800
2900
3000
3100
3200
3300
3400
3500
3600
3700
3800
3900
4000
4100
4200
4300
4400
4500
4600
4700
4800
4900
5000
5100
5200
5300
5400
5500
5600
5700
5800
5900
6000
6100
6200
6300
6400
6500
6600
6700
6800
6900
7000
7100
7200
7300
7400
7500
7600
7700
7800
7900
8000
8100
8200
8300
8400
8500
8600
8700
8800
8900
9000
9100
9200
9300
9400
9500
9600
9700
9800
9900

In [25]:
data_df = pd.DataFrame(dist_dict)
data_df.head()

   frame  dist_to_kd  dist_to_atp
0      0  181.523840   134.522021
1      1  138.477302   124.663946
2      2  180.236006   141.397940
3      3  128.659420   129.687877
4      4  149.033662   115.940074

In [26]:
data_df[['dist_to_kd']].idxmin()

dist_to_kd    6253
dtype: int64

In [30]:
data_df[['dist_to_atp']].idxmin()

dist_to_atp    8699
dtype: int64

In [35]:
data_df.nsmallest(20, "dist_to_atp")

      frame  dist_to_kd  dist_to_atp
8699   8699  105.748128    45.048154
7527   7527  103.409467    46.523883
5017   5017  104.840029    47.200701
6860   6860   95.944184    47.929287
4500   4500  112.809976    48.070194
489     489  103.448702    48.632855
9590   9590  106.137748    48.721556
9958   9958  111.071401    48.802505
9959   9959  111.071401    48.802505
9965   9965  111.071401    48.802505
2673   2673  105.886893    49.137098
2686   2686  105.886893    49.137098
9849   9849  101.979783    49.383363
6913   6913  106.414014    49.704732
6917   6917  106.414014    49.704732
4363   4363  110.080374    49.875479
9864   9864  110.763636    50.116101
2296   2296  108.223826    50.253005
5562   5562  107.827309    50.518623
5569   5569  107.827309    50.518623

#### Prune structures where the Akt copies flip sides.

In [8]:
ref_pdb_file = Path(Path.home(), "mtorc2/manuscript/submission_2/models/126_0_1/cluster.0/cluster_center_model.pdb")
m_ref = IMP.Model()
s_ref = IMP.atom.AllPDBSelector()
h_ref = IMP.atom.read_pdb(str(ref_pdb_file), m_ref)

sel_ref = IMP.atom.Selection(h_ref, resolution=1, molecule="AKT1", copy_index=0)
pids_ref = [pid for pid in sel_ref.get_selected_particle_indexes()]
xyzs_ref = [IMP.core.XYZ(m_ref, pid) for pid in pids_ref]

In [ ]:
gsms_edit_dir = Path("/wynton/group/sali/mhancock/mtorc2/samples/exp_14/129/analysis/1/sampcon_3/gsms/10000R_edit/")


for file in ["A", "B"]: 
    print(file)
    rmf_file_edit = Path(gsms_edit_dir, "{}.rmf3".format(file))
    fh_edit = RMF.create_rmf_file(str(rmf_file_edit))

    rmf_file = Path(gsms_dir, "{}.rmf3".format(file))
    fh = RMF.open_rmf_file_read_only(str(rmf_file))
    
    txt_file_edit = Path(gsms_edit_dir, "{}.txt".format(file))
    fh_txt_out = open(txt_file_edit, "w")
    
    txt_file = Path(gsms_dir, "{}.txt".format(file))
    fh_txt = open(txt_file, "r")
    
    m = IMP.Model()
    h = IMP.rmf.create_hierarchies(fh, m)[0]

    IMP.rmf.add_hierarchy(fh_edit, h)

    for i in range(1000):
        IMP.rmf.load_frame(fh, RMF.FrameID(i))
        score = float(fh_txt.readline())
        
        sel_0 = IMP.atom.Selection(h, resolution=1, molecule="AKT1", copy_index=0)
        pids_0 = [pid for pid in sel_0.get_selected_particle_indexes()]
        xyzs_0 = [IMP.core.XYZ(m, pid) for pid in pids_0]

        sel_1 = IMP.atom.Selection(h, resolution=1, molecule="AKT1", copy_index=1)
        pids_1 = [pid for pid in sel_1.get_selected_particle_indexes()]
        xyzs_1 = [IMP.core.XYZ(m, pid) for pid in pids_1]
        
        rmsd_0 = IMP.atom.get_rmsd(xyzs_ref, xyzs_1)
        rmsd_1 = IMP.atom.get_rmsd(xyzs_ref, xyzs_2)
        
        if rmsd_1 > rmsd_0: 
            print(i, score, rmsd)
        else: 
            print(i, score)
            IMP.rmf.save_frame(fh_edit)
            fh_txt_out.write(str(score) + "\n")
            
    fh_txt_out.close()

    del fh
    del fh_edit