In [1]:
import pandas as pd
from pathlib import Path

In [2]:
xl_sat_file = Path(Path.home(), "Documents/mtorc2/data/xlms/all_xl.csv")
xl_df = pd.read_csv(xl_sat_file)
xl_df = xl_df.drop(columns=["Unnamed: 0"])
xl_df.head()

    prot1  res1   prot2  res2
0    MTOR  1197  RICTOR   516
1    MTOR  1218  RICTOR   516
2  RICTOR  1642   MSIN1   102
3  RICTOR  1092    MTOR  1993
4  RICTOR  1642   MSIN1   104

In [3]:
# Flip MTOR so that it is always prot1. 
for i in range(len(xl_df)): 
    if xl_df.iloc[i, xl_df.columns.get_loc("prot2")] == "MTOR": 
        prot1_copy = xl_df.iloc[i, xl_df.columns.get_loc("prot1")]
        res1_copy = xl_df.iloc[i, xl_df.columns.get_loc("res1")]
        
        xl_df.iloc[i, xl_df.columns.get_loc("prot1")] = xl_df.iloc[i, xl_df.columns.get_loc("prot2")]
        xl_df.iloc[i, xl_df.columns.get_loc("res1")] = xl_df.iloc[i, xl_df.columns.get_loc("res2")]

        xl_df.iloc[i, xl_df.columns.get_loc("prot2")] = prot1_copy
        xl_df.iloc[i, xl_df.columns.get_loc("res2")] = res1_copy

In [4]:
xl_df.head()

    prot1  res1   prot2  res2
0    MTOR  1197  RICTOR   516
1    MTOR  1218  RICTOR   516
2  RICTOR  1642   MSIN1   102
3    MTOR  1993  RICTOR  1092
4  RICTOR  1642   MSIN1   104

In [5]:
target_xls = list() 
for i in range(len(xl_df)):
    prot1, res1, prot2, res2 = tuple(xl_df.iloc[i])

    if prot1 == "MSIN1" and (res1 >= 158 and res1 < 280): 
        xl_df.iloc[i, xl_df.columns.get_loc("prot1")] = "CRIM"
        xl_df.iloc[i, xl_df.columns.get_loc("res1")] = res1-158+1 
    if prot2 == "MSIN1" and (res2 >= 158 and res2 < 280): 
        xl_df.iloc[i, xl_df.columns.get_loc("prot2")] = "CRIM"
        xl_df.iloc[i, xl_df.columns.get_loc("res2")] = res2-158+1   
        
    if prot1 == "MSIN1" and (res1 >= 280 and res1 < 382): 
        xl_df.iloc[i, xl_df.columns.get_loc("prot1")] = "RBD"
        xl_df.iloc[i, xl_df.columns.get_loc("res1")] = res1-280+1
    if prot2 == "MSIN1" and (res2 >= 280 and res2 < 382): 
        xl_df.iloc[i, xl_df.columns.get_loc("prot2")] = "RBD"
        xl_df.iloc[i, xl_df.columns.get_loc("res2")] = res2-280+1
        
    if prot1 == "MSIN1" and (res1 >= 382): 
        xl_df.iloc[i, xl_df.columns.get_loc("prot1")] = "MSIN1PH"
        xl_df.iloc[i, xl_df.columns.get_loc("res1")] = res1-382+1
    if prot2 == "MSIN1" and (res2 >= 382): 
        xl_df.iloc[i, xl_df.columns.get_loc("prot2")] = "MSIN1PH"
        xl_df.iloc[i, xl_df.columns.get_loc("res2")] = res2-382+1
        
    if prot1 == "AKT1" and res1 < 146: 
        xl_df.iloc[i, xl_df.columns.get_loc("prot1")] = "AKT1PH"
    if prot2 == "AKT1" and res2 < 146: 
        xl_df.iloc[i, xl_df.columns.get_loc("prot2")] = "AKT1PH"
        
    if prot1 == "AKT1" and res1 >= 146: 
        xl_df.iloc[i, xl_df.columns.get_loc("prot1")] = "KINASE"
        xl_df.iloc[i, xl_df.columns.get_loc("res1")] = res1-146+1 
    if prot2 == "AKT1" and res2 >= 146: 
        xl_df.iloc[i, xl_df.columns.get_loc("prot2")] = "KINASE"
        xl_df.iloc[i, xl_df.columns.get_loc("res2")] = res2-146+1              

#     if prot1 in ["RICTOR", "MTOR"] and prot2 in ["AKT1"]: 
#         continue 
#     if prot2 in ["RICTOR", "MTOR"] and prot1 in ["AKT1"]: 
#         continue
#     if prot1 in ["AKT1"] and prot2 in ["AKT1"]: 
#         continue  

    target_xls.append(i)

In [6]:
# # RICTOR 97 - KINASE 232
# target_xls.remove(32)
# # RICTOR 11 - KINASE 177
# target_xls.remove(54)

In [7]:
print(len(target_xls))

220

In [8]:
xl_df = xl_df.iloc[target_xls].copy() 
# df_copy = df_copy.drop(columns=["contains", "satisfied"])
for i in range(len(xl_df)): 
    print(tuple(xl_df.iloc[i]))

('MTOR', 1197, 'RICTOR', 516)
('MTOR', 1218, 'RICTOR', 516)
('RICTOR', 1642, 'MSIN1', 102)
('MTOR', 1993, 'RICTOR', 1092)
('RICTOR', 1642, 'MSIN1', 104)
('MTOR', 1186, 'RICTOR', 516)
('AKT1PH', 30, 'RICTOR', 11)
('MTOR', 2045, 'RICTOR', 1477)
('MTOR', 1186, 'RICTOR', 507)
('MTOR', 1218, 'RICTOR', 507)
('MSIN1PH', 41, 'MLST8', 215)
('AKT1PH', 30, 'RICTOR', 813)
('MTOR', 42, 'RICTOR', 1382)
('MSIN1', 95, 'RICTOR', 1614)
('MTOR', 2090, 'RICTOR', 1477)
('MTOR', 550, 'RICTOR', 516)
('MTOR', 533, 'KINASE', 44)
('MTOR', 1566, 'RICTOR', 1391)
('RICTOR', 1590, 'MSIN1', 104)
('KINASE', 37, 'RICTOR', 516)
('RICTOR', 719, 'KINASE', 18)
('MTOR', 1256, 'KINASE', 275)
('MTOR', 2374, 'MLST8', 86)
('MTOR', 2129, 'RICTOR', 1312)
('MLST8', 313, 'CRIM', 19)
('KINASE', 38, 'RBD', 34)
('MTOR', 2113, 'RICTOR', 274)
('RICTOR', 813, 'KINASE', 18)
('MTOR', 84, 'RICTOR', 699)
('MTOR', 309, 'MSIN1', 132)
('RBD', 38, 'RICTOR', 1095)
('KINASE', 9, 'CRIM', 18)
('KINASE', 232, 'RICTOR', 97)
('MTOR', 42, 'KINASE', 139)
('MTOR', 2090, 'KINASE', 44)
('KINASE', 131, 'RICTOR', 800)
('RICTOR', 566, 'RBD', 38)
('CRIM', 9, 'MLST8', 307)
('MTOR', 1458, 'RICTOR', 1119)
('MSIN1', 132, 'MLST8', 322)
('MTOR', 1458, 'RICTOR', 1082)
('MTOR', 1458, 'RICTOR', 1095)
('MTOR', 1218, 'RICTOR', 517)
('MTOR', 1457, 'MSIN1PH', 41)
('MTOR', 1458, 'RICTOR', 1080)
('KINASE', 38, 'RBD', 16)
('MTOR', 1457, 'RICTOR', 1095)
('MSIN1', 147, 'MLST8', 305)
('MTOR', 1766, 'RICTOR', 586)
('MTOR', 2113, 'RICTOR', 270)
('MTOR', 1458, 'RICTOR', 1107)
('MTOR', 2045, 'RICTOR', 1464)
('MTOR', 1472, 'RICTOR', 1119)
('RICTOR', 545, 'KINASE', 18)
('KINASE', 177, 'RICTOR', 11)
('MTOR', 2370, 'RICTOR', 126)
('MSIN1PH', 41, 'KINASE', 25)
('MTOR', 2218, 'MTOR', 900)
('RBD', 38, 'RBD', 23)
('KINASE', 18, 'KINASE', 38)
('KINASE', 44, 'KINASE', 156)
('KINASE', 18, 'KINASE', 156)
('RICTOR', 791, 'RICTOR', 813)
('MTOR', 251, 'MTOR', 379)
('RICTOR', 791, 'RICTOR', 813)
('MTOR', 301, 'MTOR', 42)
('AKT1PH', 30, 'KINASE', 25)
('AKT1PH', 30, 'KINASE', 38)
('MSIN1PH', 73, 'MSIN1PH', 120)
('RICTOR', 764, 'RICTOR', 800)
('RICTOR', 791, 'RICTOR', 826)
('MTOR', 2496, 'MTOR', 2437)
('AKT1PH', 30, 'KINASE', 13)
('MTOR', 1745, 'MTOR', 1655)
('KINASE', 44, 'KINASE', 18)
('MTOR', 42, 'MTOR', 128)
('RICTOR', 374, 'RICTOR', 734)
('RICTOR', 541, 'RICTOR', 582)
('MSIN1PH', 37, 'MSIN1PH', 6)
('RICTOR', 800, 'RICTOR', 856)
('MTOR', 42, 'MTOR', 298)
('KINASE', 9, 'KINASE', 23)
('KINASE', 34, 'KINASE', 38)
('RICTOR', 516, 'RICTOR', 507)
('RICTOR', 800, 'RICTOR', 734)
('KINASE', 13, 'KINASE', 38)
('RICTOR', 921, 'RICTOR', 856)
('RICTOR', 1107, 'RICTOR', 1119)
('RICTOR', 791, 'RICTOR', 826)
('KINASE', 281, 'KINASE', 139)
('MTOR', 1293, 'MTOR', 1267)
('AKT1PH', 30, 'KINASE', 244)
('RICTOR', 800, 'RICTOR', 856)
('KINASE', 69, 'KINASE', 139)
('KINASE', 162, 'KINASE', 44)
('RICTOR', 692, 'RICTOR', 719)
('RICTOR', 239, 'RICTOR', 916)
('RICTOR', 374, 'RICTOR', 800)
('RICTOR', 764, 'RICTOR', 856)
('RICTOR', 374, 'RICTOR', 734)
('KINASE', 123, 'AKT1PH', 112)
('MTOR', 226, 'MTOR', 1277)
('KINASE', 152, 'AKT1PH', 14)
('MTOR', 900, 'MTOR', 2352)
('CRIM', 119, 'RBD', 28)
('KINASE', 131, 'KINASE', 34)
('AKT1PH', 20, 'KINASE', 156)
('AKT1PH', 112, 'KINASE', 18)
('CRIM', 19, 'CRIM', 9)
('MTOR', 1257, 'MTOR', 1293)
('MTOR', 1406, 'MTOR', 2301)
('KINASE', 18, 'KINASE', 25)
('RICTOR', 516, 'RICTOR', 507)
('KINASE', 152, 'KINASE', 131)
('MTOR', 471, 'MTOR', 550)
('MSIN1PH', 83, 'MSIN1PH', 47)
('RICTOR', 1107, 'RICTOR', 1095)
('KINASE', 156, 'KINASE', 34)
('KINASE', 44, 'KINASE', 34)
('KINASE', 9, 'KINASE', 18)
('AKT1PH', 30, 'KINASE', 156)
('AKT1PH', 30, 'KINASE', 18)
('MTOR', 2090, 'MTOR', 2045)
('KINASE', 18, 'KINASE', 13)
('MTOR', 309, 'MTOR', 42)
('RICTOR', 641, 'RICTOR', 586)
('RICTOR', 1391, 'RICTOR', 813)
('RICTOR', 1281, 'RICTOR', 1312)
('MTOR', 2370, 'MTOR', 2437)
('MTOR', 2370, 'MTOR', 2166)
('MTOR', 226, 'MTOR', 1566)
('MSIN1', 102, 'MSIN1', 95)
('MTOR', 84, 'MTOR', 128)
('AKT1PH', 30, 'AKT1PH', 14)
('KINASE', 38, 'KINASE', 18)
('MTOR', 1662, 'MTOR', 898)
('RICTOR', 641, 'RICTOR', 719)
('KINASE', 44, 'AKT1PH', 30)
('RICTOR', 1107, 'RICTOR', 1119)
('RICTOR', 97, 'RICTOR', 11)
('RICTOR', 764, 'RICTOR', 791)
('MTOR', 1267, 'MTOR', 1293)
('RICTOR', 1107, 'RICTOR', 1095)
('AKT1PH', 20, 'AKT1PH', 14)
('KINASE', 162, 'KINASE', 131)
('RICTOR', 800, 'RICTOR', 734)
('RICTOR', 1080, 'RICTOR', 1095)
('MTOR', 230, 'MTOR', 1277)
('MTOR', 1655, 'MTOR', 1702)
('RICTOR', 541, 'RICTOR', 582)
('KINASE', 123, 'AKT1PH', 30)
('AKT1PH', 30, 'KINASE', 152)
('RICTOR', 1116, 'RICTOR', 1095)
('AKT1PH', 30, 'KINASE', 241)
('MTOR', 230, 'MTOR', 369)
('RICTOR', 1107, 'RICTOR', 1116)
('AKT1PH', 20, 'KINASE', 152)
('AKT1PH', 20, 'KINASE', 18)
('RICTOR', 1125, 'RICTOR', 1095)
('MTOR', 1471, 'MTOR', 1500)
('KINASE', 44, 'AKT1PH', 112)
('RICTOR', 764, 'RICTOR', 800)
('KINASE', 9, 'KINASE', 139)
('RICTOR', 1312, 'RICTOR', 1334)
('KINASE', 152, 'KINASE', 34)
('KINASE', 274, 'KINASE', 139)
('KINASE', 152, 'AKT1PH', 20)
('KINASE', 18, 'KINASE', 34)
('MTOR', 379, 'MTOR', 384)
('KINASE', 44, 'AKT1PH', 20)
('MSIN1PH', 134, 'MSIN1PH', 123)
('MTOR', 1655, 'MTOR', 898)
('RICTOR', 1080, 'RICTOR', 1095)
('RICTOR', 699, 'RICTOR', 734)
('KINASE', 162, 'KINASE', 37)
('MTOR', 251, 'MTOR', 384)
('RICTOR', 692, 'RICTOR', 719)
('KINASE', 275, 'KINASE', 139)
('KINASE', 123, 'KINASE', 34)
('KINASE', 44, 'KINASE', 152)
('KINASE', 139, 'KINASE', 281)
('AKT1PH', 30, 'AKT1PH', 20)
('KINASE', 38, 'KINASE', 37)
('RICTOR', 998, 'RICTOR', 507)
('KINASE', 123, 'KINASE', 156)
('CRIM', 119, 'MSIN1PH', 120)
('MTOR', 471, 'MTOR', 425)
('KINASE', 162, 'KINASE', 34)
('MTOR', 309, 'MTOR', 1566)
('KINASE', 162, 'AKT1PH', 20)
('RICTOR', 781, 'RICTOR', 813)
('AKT1PH', 39, 'AKT1PH', 14)
('KINASE', 38, 'KINASE', 34)
('KINASE', 44, 'KINASE', 23)
('RICTOR', 838, 'RICTOR', 856)
('RICTOR', 1082, 'RICTOR', 1107)
('KINASE', 162, 'KINASE', 18)
('MTOR', 1256, 'MTOR', 985)
('RICTOR', 890, 'RICTOR', 1391)
('RICTOR', 1304, 'RICTOR', 1095)
('KINASE', 162, 'KINASE', 13)
('KINASE', 162, 'AKT1PH', 14)
('MTOR', 1745, 'MTOR', 298)
('MTOR', 2496, 'MTOR', 2470)
('MTOR', 1868, 'MTOR', 1805)
('RICTOR', 1312, 'RICTOR', 1092)
('MTOR', 2496, 'MTOR', 2489)
('MSIN1PH', 37, 'MSIN1PH', 45)
('MTOR', 2218, 'MTOR', 1662)
('RICTOR', 1125, 'RICTOR', 1116)
('MTOR', 1293, 'MTOR', 1256)
('RICTOR', 374, 'RICTOR', 800)
('AKT1PH', 30, 'KINASE', 232)
('MTOR', 384, 'MTOR', 425)
('MTOR', 309, 'MTOR', 298)
('AKT1PH', 140, 'KINASE', 69)
('MTOR', 1256, 'MTOR', 980)
('RICTOR', 781, 'RICTOR', 813)
('MTOR', 2370, 'MTOR', 309)
('RICTOR', 1092, 'RICTOR', 1107)

In [9]:
xl_df.to_csv(Path(Path.home(), "Documents/mtorc2/data/xlms/all_xls.domain.csv"))