In [2]:
import pandas as pd

In [3]:
xl_file = "/Users/matthew/Documents/mtorc2/data/xlms/xl_intra.csv"
xl_df = pd.read_csv(xl_file)

In [4]:
xl_df = xl_df.dropna(subset=["Proteins"])

In [5]:
xl_df.head()

,Linker,Title,Charge,Precursor_Mass,Peptide_Mass,Modifications,Score,Precursor_Mass_Error(Da),Precursor_Mass_Error(ppm),Peptide,Proteins,Unnamed: 11
0,DSS,mTORC_Akt_DSSCX_insol_2ug_run1_121820.7396.739...,5.0,2393.3,2393.31,NaN,2.530000e-12,-0.004731,-1.976762,HKVNIGMIDQSR(2)-KNLSIQR(1),mTOR(900)-mTOR(2218)/,NaN
1,NaN,mTORC_Akt_DSSCX_insol_2ug_run1_121820.8299.829...,5.0,2550.0,2550.00,NaN,3.810000e-11,-0.005239,-2.057384,KGSQKVSGPQYR(5)-VTMKEILLK(4),mSIN1(317)-mSIN1(302)/,NaN
2,NaN,mTORC_Akt_DSSCX_insol_2ug_run1_121820.8786.878...,4.0,1990.0,1990.00,NaN,2.240000e-10,-0.003502,-1.764018,GTFGKVILVK(5)-KEVIVAK(1),AKT1(163)-AKT1(183)/,NaN
3,NaN,mTORC_Akt_DSSCX_insol_2ug_run1_121820.8937.893...,4.0,3110.0,3110.00,NaN,2.660000e-10,-0.004127,-1.326752,EVIVAKDEVAHTLTENR(6)-EGIKDGATMK(4),AKT1(189)-AKT1(301)/,NaN
4,NaN,mTORC_Akt_DSSCX_insol_2ug_run1_121820.8921.892...,4.0,2250.0,2250.00,NaN,5.790000e-10,-0.002683,-1.193366,GTFGKVILVK(5)-EGIKDGATMK(4),AKT1(163)-AKT1(301)/,NaN

In [6]:
entries = list() 
for entry in xl_df["Proteins"]: 
    prot1 = entry.split("-")[0].split("(")[0].upper()
    prot2 = entry.split("-")[1].split("(")[0].upper()
    
    if prot1 == "RICTR": 
        prot1 = "RICTOR"
    if prot2 == "RICTR": 
        prot2 = "RICTOR"
    
    res1 = entry.split("-")[0].split("(")[1].split(")")[0]
    res2 = entry.split("-")[1].split("(")[1].split(")")[0]
    
    entries.append([prot1, res1, prot2, res2])

In [7]:
xl_df_new = pd.DataFrame(data=entries, columns=["prot1", "res1", "prot2", "res2"])
xl_df_new.head()

   prot1 res1  prot2  res2
0   MTOR  900   MTOR  2218
1  MSIN1  317  MSIN1   302
2   AKT1  163   AKT1   183
3   AKT1  189   AKT1   301
4   AKT1  163   AKT1   301

In [8]:
xl_df_new.to_csv("/Users/matthew/Documents/mtorc2/data/xlms/xl_intra_dss_formatted.csv", sep=",")